apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: supes2messagehub
spec:
  dependencies:
    - camel:jslt
    - mvn:io.quarkus:quarkus-apicurio-registry-avro
  traits:
    mount:
      configuration:
        resources:
          - configmap:supes2messagehub
  flows:
    - from:
        uri: kafka:{{superheroes.kafka.topic.name}}
        parameters:
          additionalProperties.apicurio.registry.avro-datum-provider: '{{superheroes.apicurio.datumprovider}}'
          additionalProperties.apicurio.registry.url: '{{superheroes.apicurio.registryurl}}'
          brokers: '{{superheroes.kafka.brokers}}'
          clientId: '{{superheroes.kafka.clientId}}'
          groupId: '{{superheroes.kafka.groupId}}'
          valueDeserializer: '{{superheroes.kafka.valueDeserializer}}'
        steps:
        - convert-body-to: String

        - log: 'Raw fight: ${body}'

        - to:
            uri: jslt:supes2messagehub/supes2messagehub.jslt
            parameters:
              prettyPrint: "true"

        - log: |-
            Fight result sent to MessageHub:
            ${body}

        - to:
            uri: kafka:{{messagehub.kafka.topic.name}}
            parameters:
              brokers: '{{messagehub.kafka.brokers}}'
              clientId: '{{messagehub.kafka.clientId}}'

